### ISSUE TITLE
Use new nf-validation plugin to check samplesheet input

### ISSUE THREAD

**Issue by azmigueldario** [cidgoh/bacpaq#10]
### Description of feature

We can try to setup the workflow to validate input sample sheet using a new plugin from the nf-core community

https://nextflow-io.github.io/nf-validation/

**Comment by davidtong28** [comment]
Hi Miguel, will this feature correct the error found in #6 ?

**Comment by anwarMZ** [comment]
We tried that but its kind of a redundant process and offers less flexibility because we have updated the `https://github.com/cidgoh/nf-seqqc/blob/master/bin/check_samplesheet.py` to accommodate the nanopore data column in samplesheet.csv. We can revisit the implementation of [nf-validation](https://nextflow-io.github.io/nf-validation/) if we can update the schema to accept nanopore data.

**Comment by anwarMZ** [comment]
Reopening this: nf-validation plugin can help validate the samplesheet and create the channel from it -  use [this](https://nextflow-io.github.io/nf-validation/samplesheets/fromSamplesheet/#basic-example) as an example.

**Comment by anwarMZ** [comment]
For seqqc workflow - 

Add 4 columns to the Samplesheet (combined for short and long reads). The path to long_reads and short_reads_2 is optional. Valid examples could look like the following:
`sample,group,short_reads_1,short_reads_2,long_reads
sample1,0,data/sample1_R1.fastq.gz,data/sample1_R2.fastq.gz,data/sample1
sample2,0,data/sample2_R1.fastq.gz,data/sample2_R2.fastq.gz,data/sample2
sample3,1,data/sample3_R1.fastq.gz,data/sample3_R2.fastq.gz,`
